config/routes.rb
require 'resque/server'
Rails.application.routes.draw do
  get 'payments/index'
  get 'payments/new'
  get 'transacations/index'
 
  get 'wallets/index'
  get 'bookings/new'
  get 'bookings/index'
  get 'reservations/index'
  get 'reservations/show'
  get 'reservations/new'
  get 'reservations/edit'
  # get 'employees/index'
  # get 'employees/show'
  # get 'employees/new'
  # get 'employees/edit'
  get 'employees/allemployee'
  # get 'rooms/index'
  # get 'rooms/show'
  # get 'rooms/new'
  # get 'rooms/edit'
  # get 'hotels/index'
  # get 'hotels/new'
  # get 'hotels/edit'

  # post '/rooms', to: 'rooms#create'
  devise_for :users
  
  root 'main#home'
  get 'main/display', to: 'main#display'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :hotels do
    resources :rooms do 
    end
    resources :employees
    collection do
      post 'import_csv'
    end
    # resources :employees, only: [:index, :new, :create]
  end
  # resources :bookings, only: [:index, :new, :create, :show, :edit, :update, :destroy]

  resources :bookings 
  
  resources :payments
  
  # resources :payments

  resources :dashboard

  resources :checkout, only: [:create]

  resources :main

  authenticate :user do
    mount Resque::Server.new, at: '/jobs'
  end

  # authenticate :user, -> (u) {u.id == 11} do
  #   mount Resque::Server.new, at: '/jobs'
  # end


  # resources :products

  post 'checkout/create', to: 'checkout#create'
  # resources :checkout




  get 'rooms/allrooms', to: 'rooms#allrooms';
  get 'rooms/roominsidehotel', to: 'rooms#roominsidehotel';


  get 'main/hotelrooms/:hotel_id', to: 'main#hotelrooms', as: 'test'

  get 'rooms/hotelallrooms', to: 'rooms#hotelallrooms'

  # get 'payments/new', to: 'payments#new'
  # get 'payments/create', to: 'payments#create'

  resources :payments
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :room
  belongs_to :user
  has_many :payments
  has_one :wallet

  # validates :check_in_date, :check_out_date, presence: true
  # validate :check_out_after_check_in
  # validate :check_room_availability

  # validates_uniqueness_of :room_id, scope: :date

  # private

  # def check_out_after_check_in
  #   return if check_in_date.blank? || check_out_date.blank?

  #   errors.add(:check_out_date, 'must be after check-in date') if check_out_date <= check_in_date
  # end

  # def check_room_availability
  #   return if room.nil?

  #   overlapping_bookings = room.bookings.where(
  #     "(check_in_date <= ? AND check_out_date >= ?) OR (check_in_date <= ? AND check_out_date >= ?)",
  #     check_in_date, check_in_date, check_out_date, check_out_date)

  #   errors.add(:base, 'Room is not available for the selected dates') if overlapping_bookings.exists?
  # end
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :hotel

  
end

app/models/hotel.rb
# require 'csv'

class Hotel < ApplicationRecord
    has_many :rooms, dependent: :destroy
    has_many :employees, dependent: :destroy
    # has_many :bookings, dependent: :destroy

  
    has_one_attached :hotel_photo, dependent: :destroy 
    
    # def self.to_csv 
    #     # attributes = %w{name address contact_number email description}
    #     attributes = Hotel.column_names
        
    #     CSV.generate(headers: true) do |csv|
    #     csv << attributes 

    #         all.each do |employee|
    #             csv << attributes.map {|attr| employee.send(attr)}
    #         end
    #     end
    # end 
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :booking
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/room.rb
require 'csv'
class Room < ApplicationRecord
  belongs_to :hotel
  has_one_attached :room_photo
  has_many :bookings, dependent: :destroy 


  # enum status: { available: 0, booked: 1 }

  # def available?
  #   status == 'available'
  # end




  
  def available?(check_in_date, check_out_date)
    overlapping_bookings = bookings.where(
      "(check_in_date <= ? AND check_out_date >= ?) OR (check_in_date <= ? AND check_out_date >= ?)",
      check_in_date, check_in_date, check_out_date, check_out_date
    )

    overlapping_bookings.empty?
  end
  
end
 

app/models/transacation.rb
class Transacation < ApplicationRecord
  belongs_to :user
  
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_many :bookings

    has_one :wallet
    has_many :transacations
end
 

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :booking
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
    
    @rooms = Room.all

    @hotels = Hotel.all

  end

  def show 
    @room = Room.find(params[:id])
   
  end

  def roomdisplay
    @rooms = Room.find(params[:id])
  end

  def hotelrooms 
    @hotel = Hotel.find(params[:hotel_id])
    puts @hotel
    @rooms = @hotel.rooms
    puts "========================="
    puts @room



  end

  def book 
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/main/book.html.erb
 <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
          Book Now
</button>

      
<!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
                <button t ype="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <form action="">
                  <div class="form-group">
                    <label for="">Choose hotel</label>
                    <input type="text" name="" class="form-control">
                   
                    

                  </div>

                  <div class="form-group">
                    <label for="">Check-in date</label>
                    <input type="text" name="" class="form-control">
                  </div>

                  <div class="form-group">
                    <label for="">Check-out date</label>
                    <input type="text" name="" class="form-control">
                  </div>

                  <div class="form-group">
                    <label for="">Adult</label>
                    <input type="text" name="" class="form-control">
                  </div>

                  <div class="form-group">
                    <label for="">Children</label>
                    <input type="text" name="" class="form-control">
                  </div>
                </form>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
              </div>
            </div>
          </div>
        </div>

app/views/main/display.html.erb
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
  <h1 class="navbar-brand fs-1  fw-bold table table-rounded" href="#" style="text-align :center">Admin Dashboard</h1>
</nav>

<!-- Sidebar -->
<div class="container-fluid">
  <div class="row">
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <!-- Sidebar components, links, and navigation items -->
      <!-- Add sidebar links, icons, and components as needed -->
    </nav>
    <!-- Main content area -->
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
      <!-- Main content, cards, tables, forms, and components -->
      <!-- Add content, functionalities, and components as needed -->
    </main>
  </div>
</div>


<div class='d-flex p-5'  >
<div style="margin-right :40px">

<div class="card mt-5" style="width: 18rem">
  <%# <img src="..." class="card-img-top" alt="..."> %>
  <div class="card-body">
    <h2 class="card-title justified-content-center">Hotel Listing</h2>
    <p class="card-text">Indulge in a memorable stay at our hotel, blending modern amenities with timeless charm.</p>
    <%# <a href="#" class="btn btn-primary">Go somewhere</a> %>
    <%# <%= link_to 'Go somewhere', hotels_index_path, class: 'btn btn-success' %>
    <%= link_to 'Go somewhere', hotels_path, class: 'btn btn-warning' %>

  </div>
</div>

</div>


<div style="margin-right :40px">
<div class="card mt-5 " style="width: 18rem;">
  <%# <img src="..." class="card-img-top" alt="..."> %>
  <div class="card-body">
    <h2 class="card-title justified-content-center">Total Rooms</h2>
    <p class="card-text">Indulge in a memorable stay at our hotel, blending modern amenities with timeless charm.</p>
    <%# <a href="#" class="btn btn-primary">Go somewhere</a> %>
    <%= link_to 'Go somewhere', rooms_allrooms_path, class: 'btn btn-success' %>
  </div>
</div>

</div>

<div class="card mt-5" style="width: 18rem;">
  <%# <img src="..." class="card-img-top" alt="..."> %>
  <div class="card-body">
    <h2 class="card-title justified-content-center">All Employee</h2>
    <p class="card-text">Indulge in a memorable stay at our hotel, blending modern amenities with timeless charm.</p>
    <%# <a href="#" class="btn btn-primary">Go somewhere</a> %>
    <%= link_to 'Go somewhere', employees_allemployee_path, class: 'btn btn-primary' %>
  </div>
</div>

</div>


<div class="d-flex p-5">

<div style="margin-right :40px">


  <div class="card mt-5" style="width: 18rem;">
  <%# <img src="..." class="card-img-top" alt="..."> %>
  <div class="card-body">
    <h2 class="card-title justified-content-center">downloade csv</h2>
    <p class="card-text">Indulge in a memorable stay at our hotel, blending modern amenities with timeless charm.</p>
    <%# <a href="#" class="btn btn-primary">Go somewhere</a> %>
    <%= link_to 'downloadeCSV', hotels_path(format: :csv), class: 'btn btn-primary' %>
  </div>
</div>

</div>


<div style="margin-right :40px">

<div class="card mt-5" style="width: 18rem;">
  <%# <img src="..." class="card-img-top" alt="..."> %>
  <div class="card-body">
    <h2 class="card-title justified-content-center">All Employee</h2>
    <p class="card-text">Indulge in a memorable stay at our hotel, blending modern amenities with timeless charm.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
</div>


<div class="card mt-5" style="width: 18rem;">
  <%# <img src="..." class="card-img-top" alt="..."> %>
  <div class="card-body">
    <h2 class="card-title justified-content-center">All Employee</h2>
    <p class="card-text">Indulge in a memorable stay at our hotel, blending modern amenities with timeless charm.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

</div>

app/views/main/home.html.erb
<%# 
<h1>Main#home</h1>
<p>Find me in app/views/main/home.html.erb</p> %>

<!--

<% if current_user %>
    Hello <%= current_user.email %>
<% end %>

-->

<%= image_tag 'banner.jpg', class: 'w-100 h-100 ' %>

<!-- our hotels -->
      <div  class="our_room" id="rooms">
         <div class="container">
            <div class="row">
               <div class="col-md-12">
                  <div class="titlepage">
                     <h2>Our Hotels</h2>
                     <p>Lorem Ipsum available, but the majority have suffered </p>
                  </div>
               </div>
            </div>

            <div class="row">
            
               <% @hotels.each do |hotel| %>
               <div class="card">
               <div class="col-md-4 col-sm-6 d-flex ">
                  <div id="serv_hover"  class="room">

                     <div class="room_img">
                        <%= image_tag hotel.hotel_photo %>
                     </div>

                    
                     <div class="bed_room">
                        <h3>Hotel Name : <%= hotel.name %> </h3>
                        <p>hotel address : <%= hotel.address %></p>
                        <%# <%= link_to 'Book Now', new_dashboard_path, class: 'btn btn-primary' %>
                        <%= link_to 'Click me', test_path(hotel), class: 'btn btn-primary' %>
                        <%= link_to 'Payment', checkout_create_path(hotel_id: hotel.id), class: 'btn btn-primary' %>

                     </div>

                  </div>
               </div>
               </div>
                  <% end %>
               
              
            </div>
         </div>
      </div>
<!-- end our hotels -->


 <!-- about -->
      <div class="about" id="about">
         <div class="container-fluid">
            <div class="row">
               <div class="col-md-5">
                  <div class="titlepage">
                     <h2>About Us</h2>
                     <p>The passage experienced a surge in popularity during the 1960s when Letraset used it on their dry-transfer sheets, and again during the 90s as desktop publishers bundled the text with their software. Today it's seen all around the web; on templates, websites, and stock designs. Use our generator to get your own, or read on for the authoritative history of lorem ipsum. </p>
                     <a class="read_more btn btn-outline-primary" href="Javascript:void(0)"> Read More</a>
                  </div>
               </div>
               <div class="col-md-7">
                  <div class="about_img">
                     <%# <figure><img src="images/about.png" alt="#"/></figure> %>
                     <%= image_tag 'about.png', class: 'img-fluid' %>
                  </div>
               </div>
            </div>
         </div>
      </div>
<!-- end about -->

       
  <div class="dropdown">
        <a class="nav-item active dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Hotels
        </a>
        
        <ul class="dropdown-menu">
          <% @hotels.each do |hotel| %>
            <li class= "dropdown-item">
                    <%= link_to  hotel.name, hotel_rooms_path(hotel)%>
            </li>
            <% end %>
        </ul>
      </div>


<!-- our_room -->
      <div  class="our_room" id="rooms">
         <div class="container">
            <div class="row">
               <div class="col-md-12">
                  <div class="titlepage">
                     <h2>Our Room</h2>
                     <p>Lorem Ipsum available, but the majority have suffered </p>
                  </div>
               </div>
            </div>

            <div class="row">
            
               <% @rooms.each do |room| %>
               <div class="col-md-4 col-sm-6 d-flex ">
                  <div id="serv_hover"  class="room">

                     <div class="room_img">
                        <%= image_tag room.room_photo %>

                     </div>
                     <div class="bed_room">
                        <h3>Room Price : <%= room.price %> </h3>
                        <p>Room_type : <%= room.room_type %></p>
                        <%# <%= link_to 'Book Now', new_dashboard_path, class: 'btn btn-primary' %>
                        <%= link_to 'Book Now', bookings_new_path, class: 'btn btn-primary' %>

                        
                     </div>

                  </div>
               </div>
                  <% end %>
               
              
               
               
            </div>
         </div>
      </div>
      <!-- end our_room -->



     
      
      


      <!-- blog -->
      <div  class="blog" id="blog">
         <div class="container">
            <div class="row">
               <div class="col-md-12">
                  <div class="titlepage">
                     <h2>Blog</h2>
                     <p>Lorem Ipsum available, but the majority have suffered </p>
                  </div>
               </div>
            </div>
            <div class="row">
               <div class="col-md-4">
                  <div class="blog_box">
                     <div class="blog_img">
                        <%# <figure><img src="images/blog1.jpg" alt="#"/></figure> %>
                        <%= image_tag 'blog1.jpg' %>
                     </div>
                     <div class="blog_room">
                        <h3>Bed Room</h3>
                        <span>The standard chunk </span>
                        <p>If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generatorsIf you are   </p>
                     </div>
                  </div>
               </div>
               <div class="col-md-4">
                  <div class="blog_box">
                     <div class="blog_img">
                        <%# <figure><img src="images/blog2.jpg" alt="#"/></figure> %>
                        <%= image_tag 'blog2.jpg' %>
                     </div>
                     <div class="blog_room">
                        <h3>Bed Room</h3>
                        <span>The standard chunk </span>
                        <p>If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generatorsIf you are   </p>
                     </div>
                  </div>
               </div>occupancy
               <div class="col-md-4">
                  <div class="blog_box">
                     <div class="blog_img">
                        <%# <figure><img src="images/blog3.jpg" alt="#"/></figure> %>
                        <%= image_tag 'blog3.jpg' %>
                     </div>
                     <div class="blog_room">
                        <h3>Bed Room</h3>
                        <span>The standard chunk </span>
                        <p>If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generatorsIf you are   </p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- end blog -->


      


<!--  footer -->
      <footer>
         <div class="footer">
            <div class="container">
               <div class="row">
                  <div class=" col-md-4">
                     <h3>Contact US</h3>
                     <ul class="conta">
                        <li><i class="fa fa-map-marker" aria-hidden="true"></i> Address</li>
                        <li><i class="fa fa-mobile" aria-hidden="true"></i> +01 1234569540</li>
                        <li> <i class="fa fa-envelope" aria-hidden="true"></i><a href="#"> demo@gmail.com</a></li>
                     </ul>
                   </div>
                  <div class="col-md-4">
                     <h3>Menu Link</h3>
                     <ul class="link_menu">
                        <li class="active"><a href="#">Home</a></li>
                        <li><a href="about.html"> about</a></li>
                        <li><a href="room.html">Our Room</a></li>
                        <li><a href="contact.html">Contact Us</a></li>
                     </ul>
                  </div>
                  <div class="col-md-4">
                     <h3>News letter</h3>
                     <form class="bottom_form">
                        <input class="enter" placeholder="Enter your email" type="text" name="Enter your email">
                        <button class="sub_btn">subscribe</button>
                     </form>
                     <ul class="social_icon">
                        <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
                     </ul>
                  </div>
               </div>
            </div>
            <div class="copyright">
               <div class="container">
                  <div class="row">
                     <div class="col-md-10 offset-md-1">
                        
                        <p>
                        © 2013 - 24 All Rights Reserved. Design by codiatic technologies</a>
                        <br><br>
                        Distributed by <a href="http://codiatic.com/" target="_blank">CodiaticTechnologies</a>
                        </p>

                     </div>
                  </div>
               </div>
            </div>
         </div>
      </footer>
      <!-- end footer -->

app/views/main/hotelrooms.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <%# <%= stylesheet_link_tag "roomstyle" %>

</head>
<body>
    <%# <div class="container">
        <div class="row">
            <div class="col">

            <div class="card">
                <div class="first-content">
                </div>
            </div>

            <div class="second-content">
                <h1>Shose</h1><br>
                <p>Price: <i>23$</i> </p>
                <h3>70% off</h3>
                <a href="#">Order Now </a>
            </div>

            </div>
        </div>
    </div> %>

    <!-- our hotels -->
      <div  class="our_room" id="rooms">
         <div class="container">
            <div class="row">
               <div class="col-md-12">
                  <div class="titlepage">
                     <h2>Our rooms</h2>
                     <p>Lorem Ipsum available, but the majority have suffered </p>
                  </div>
               </div>
            </div>

            <div class="row">
            
               <% @rooms.each do |room| %>
               <%# <div class="card box-shadow"> %>
                <div class="col-md-4 col-sm-6 d-flex py-3 py-sm-0 ">
                    <div id="serv_hover"  class="room">

                        <div class="room_img">
                            <%= image_tag room.room_photo, class: "img-fluid rounded card-img-top" %>
                        </div>

                        <%# <div class="card-body">
                            <h1 class="card-title" >hii</h1>
                        </div> %>


                        <div class="bed_room">
                            <h3>Hotel Name : <%= room.room_type %> </h3>
                            <p>hotel address : <%= room.price %></p>
                        </div>

                        <%# <a href="#", class="btn btn-primary">Go Somewhere</a> %>
                        <%= link_to 'Click Me', main_path(room), class: 'btn btn-primary' %>
                    </div>
                </div>
                <%# </div> %>
                  <% end %>
               
              
            </div>
         </div>
      </div>
<!-- end our hotels -->
</body>
</html>

app/views/main/roomdisplay.html.erb
 <!-- about -->
      <div class="about" id="about">
         <div class="container-fluid">
            <div class="row">

            <div class="col-md-5">
                  <div class="about_img">
                     <%# <figure><img src="images/about.png" alt="#"/></figure> %>
                     <%= image_tag 'about.png', class: 'img-fluid rounded' %>
                  </div>
               </div>
               
               <div class="col-md-5">
                  <div class="titlepage">
                     <p>A room is one of the separate sections or parts of the inside of a building.  </p>
                     <p>Room Type : <%= @rooms.room_type %> </p>
                    <del>1200</del> <br>
                    900
                     <a class="read_more btn btn-outline-primary" href="Javascript:void(0)"> Book Now</a>
                  </div>
               </div>

               
            </div>
         </div>
      </div>
<!-- end about -->

app/views/main/show.html.erb
<div  class="our_room" id="rooms">
    <div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="titlepage">
                <h2>Our Room</h2>
                <p>Lorem Ipsum available, but the majority have suffered </p>
            </div>
        </div>
    </div>

        <div class="row">
           
            
            <div class="col-md-5">
                <%= image_tag @room.room_photo %>
            </div>
            <div class="col-md-4">
                <h1>Grande Room</h1>
                <h3>Room Type: <%= @room.room_type %> </h3>
                <h5>Room capacity : <%= @room.capacity %> </h5>
                <h5>Floor Number : <%= @room.floor_number %> </h5>
                <h6>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem quo quaerat aut excepturi, unde eligendi laborum delectus maiores.</h6>
            </div>
            <div class="col-md-3">
            <h3><del>Rs 450 </del></h3> <br>
                <h1 style="background: black; color: white; margin-right: 77px; ", class="rounded"><%= @room.price %>
                <%# <button class="btn btn-primary", style="width: 100px; height: 56px; font-weight: bold">Book</button> %>
                    <%= link_to 'Book', bookings_new_path(id: @room), class: 'btn btn-primary', style: "width: 100px; height: 56px; font-weight: bold" %>
                </h1>
            </div>
        </div>
    </div>
</div>