config/routes.rb
require 'resque/server'
Rails.application.routes.draw do
  get 'payments/index'
  get 'payments/new'
  get 'transacations/index'
 
  get 'wallets/index'
  get 'bookings/new'
  get 'bookings/index'
  get 'reservations/index'
  get 'reservations/show'
  get 'reservations/new'
  get 'reservations/edit'
  # get 'employees/index'
  # get 'employees/show'
  # get 'employees/new'
  # get 'employees/edit'
  get 'employees/allemployee'
  # get 'rooms/index'
  # get 'rooms/show'
  # get 'rooms/new'
  # get 'rooms/edit'
  # get 'hotels/index'
  # get 'hotels/new'
  # get 'hotels/edit'

  # post '/rooms', to: 'rooms#create'
  devise_for :users
  
  root 'main#home'
  get 'main/display', to: 'main#display'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :hotels do
    resources :rooms do 
    end
    resources :employees
    collection do
      post 'import_csv'
    end
    # resources :employees, only: [:index, :new, :create]
  end
  # resources :bookings, only: [:index, :new, :create, :show, :edit, :update, :destroy]

  resources :bookings 
  
  resources :payments
  
  # resources :payments

  resources :dashboard

  resources :checkout, only: [:create]

  resources :main

  authenticate :user do
    mount Resque::Server.new, at: '/jobs'
  end

  # authenticate :user, -> (u) {u.id == 11} do
  #   mount Resque::Server.new, at: '/jobs'
  # end


  # resources :products

  post 'checkout/create', to: 'checkout#create'
  # resources :checkout




  get 'rooms/allrooms', to: 'rooms#allrooms';
  get 'rooms/roominsidehotel', to: 'rooms#roominsidehotel';


  get 'main/hotelrooms/:hotel_id', to: 'main#hotelrooms', as: 'test'

  get 'rooms/hotelallrooms', to: 'rooms#hotelallrooms'

  # get 'payments/new', to: 'payments#new'
  # get 'payments/create', to: 'payments#create'

  resources :payments
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :room
  belongs_to :user
  has_many :payments
  has_one :wallet

  # validates :check_in_date, :check_out_date, presence: true
  # validate :check_out_after_check_in
  # validate :check_room_availability

  # validates_uniqueness_of :room_id, scope: :date

  # private

  # def check_out_after_check_in
  #   return if check_in_date.blank? || check_out_date.blank?

  #   errors.add(:check_out_date, 'must be after check-in date') if check_out_date <= check_in_date
  # end

  # def check_room_availability
  #   return if room.nil?

  #   overlapping_bookings = room.bookings.where(
  #     "(check_in_date <= ? AND check_out_date >= ?) OR (check_in_date <= ? AND check_out_date >= ?)",
  #     check_in_date, check_in_date, check_out_date, check_out_date)

  #   errors.add(:base, 'Room is not available for the selected dates') if overlapping_bookings.exists?
  # end
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :hotel

  
end

app/models/hotel.rb
# require 'csv'

class Hotel < ApplicationRecord
    has_many :rooms, dependent: :destroy
    has_many :employees, dependent: :destroy
    # has_many :bookings, dependent: :destroy

  
    has_one_attached :hotel_photo, dependent: :destroy 
    
    # def self.to_csv 
    #     # attributes = %w{name address contact_number email description}
    #     attributes = Hotel.column_names
        
    #     CSV.generate(headers: true) do |csv|
    #     csv << attributes 

    #         all.each do |employee|
    #             csv << attributes.map {|attr| employee.send(attr)}
    #         end
    #     end
    # end 
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :booking
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/room.rb
require 'csv'
class Room < ApplicationRecord
  belongs_to :hotel
  has_one_attached :room_photo
  has_many :bookings, dependent: :destroy 


  # enum status: { available: 0, booked: 1 }

  # def available?
  #   status == 'available'
  # end




  
  def available?(check_in_date, check_out_date)
    overlapping_bookings = bookings.where(
      "(check_in_date <= ? AND check_out_date >= ?) OR (check_in_date <= ? AND check_out_date >= ?)",
      check_in_date, check_in_date, check_out_date, check_out_date
    )

    overlapping_bookings.empty?
  end
  
end
 

app/models/transacation.rb
class Transacation < ApplicationRecord
  belongs_to :user
  
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_many :bookings

    has_one :wallet
    has_many :transacations
end
 

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :booking
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  
  # def allemployee 
  #   @employees = Employee.all
  # end 

  # def index
  #   @hotel = Hotel.find params[:hotel_id]
  #   @employees = @hotel.employees
  #   # @employees = Employee.all
  # end

  # def show
  #   @employee = Employee.find(params[:id])
  # end

  # def new
  #   # @employee = @hotel.employees.new
  #   @employee = Employee.new
  #   @hotel = Hotel.find(params[:hotel_id])
  # end


  # def create 
  #   @hotel = Hotel.find(params[:id])
  #   @employee = @hotel.employee.create(employee_params)
  #   if @employee.save 
  #        redirect_to @employee
  #   else
  #     render :new
  #   end
  # end 
  
  

  # def edit
    
  # end

  # def update 

  # end

  # def destroy 

  # end

  # private
  # def employee_params
  #   params.require(:employee).permit(:first_name, :last_name, :position, :salary)
  # end

  before_action :set_hotel

    def index
      @employees = @hotel.employees
    end

    def show
      @employee = Employee.find(params[:id])
    end

    def new

      @employee = @hotel.employees.build
    end

    def create
      @employee = @hotel.employees.build(employee_params)
      if @employee.save
        redirect_to admin_hotel_employees_path(@hotel), notice: 'Employee added successfully.'
      else
        render :new
      end
    end


    # def new
    #   @employee = Employee.new
    #   @hotel = Hotel.find(params[:hotel_id])
    # end
  
    # def create 
    #   @hotel = Hotel.find(params[:hotel_id])
    #   @employee = @hotel.employees.create(room_params)
    #   redirect_to hotel_path(@hotel)
    # end





    def destroy
      @employee = Employee.find(params[:id])
      @employee.destroy 

      redirect_to root_path
    end

   

    # Implement edit, update, and destroy actions
    # ...

    private

    # filter 
    def set_hotel
      @hotel = Hotel.find(params[:hotel_id])
    end

    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :salary, :position)
    end
    
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
    
    @rooms = Room.all

    @hotels = Hotel.all

  end

  def show 
    @room = Room.find(params[:id])
   
  end

  def roomdisplay
    @rooms = Room.find(params[:id])
  end

  def hotelrooms 
    @hotel = Hotel.find(params[:hotel_id])
    puts @hotel
    @rooms = @hotel.rooms
    puts "========================="
    puts @room



  end

  def book 
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/employees/_form.html.erb
<!-- app/views/admin/hotel_employees/_form.html.erb -->

<section>
  <div class='container mt-5 pt-5' >
    <div class='row' >
      <div class='col-12 col-sm-8 col-md-6 m-auto'>
        <div class='card border-0 shadow' >
          <div class='card-body'>

            <%= form_with mod: 'hotel_employee' do |form| %>
<%# [ hotel, hotel.rooms.build ] %>
              <div>
                <%= form.label :first_name %>
                <%= form.text_field :first_name, class: 'form-control my-3 py-2' %>
              </div>

              <div>
                <%= form.label :last_name %>
                <%= form.text_field :last_name, class: "form-control my-3 py-2" %>
              </div>

              <div>
                <%= form.label :position %>
                <%= form.text_field :position, class: "form-control my-3 py-2" %>
              </div>
              <div>
                <%= form.label :salary %>
                <%= form.text_field :salary, class: "form-control my-3 py-2" %>
              </div>

              <div>
                <%= form.submit %>
              </div>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/employees/allemployee.html.erb
<div class="container">
  <div class="row">
    <%# <div class="col-md-8 col-xs-12"> %>
      <div class="table-responsive">

        <h1>Listing Employee</h1>
          <table class="table table-bordered table-hover table-dark table-striped">
            <thead>
              <tr>
              <th>Employee.id</th>
                <th>First_Name</th>
                <th>Last_Name</th>
                <th>Position</th>
                <th>Salary</th>
                <%# <th colspan="3">Actions</th> %>
              </tr>
            </thead>

         <tbody>
              <% @employees.each do |employee| %>
                <tr>
                  <td><%= employee.id %></td>
                  <td><%= employee.first_name %></td>
                  <td><%= employee.last_name %></td>
                  <td><%= employee.position %></td>
                  <td><%= employee.salary %></td>
                  
               
                  
                            

                </tr>
              <% end %>
            </tbody>


          </table>

      <%# <%= link_to 'New Room', new_hotel_room_path, class: 'btn btn-outline-primary' %> 
      </div>
    </div>
  </div>
</div>

app/views/employees/edit.html.erb
<h1>Employees#edit</h1>
<p>Find me in app/views/employees/edit.html.erb</p>

app/views/employees/index.html.erb
<div class="container">
  <div class="row">
    <%# <div class="col-md-8 col-xs-12"> %>
      <div class="table-responsive">

        <h1>Listing Employee</h1>
          <table class="table table-bordered table-hover table-dark table-striped">
            <thead>
              <tr>
              <th>Employee.id</th>
                <th>First_Name</th>
                <th>Last_Name</th>
                <th>Position</th>
                <th>Salary</th>
                <th colspan="3">Actions</th>
              </tr>
            </thead>

         <tbody>
              <% @employees.each do |employee| %>
                <tr>
                  <td><%= employee.id %></td>
                  <td><%= employee.first_name %></td>
                  <td><%= employee.last_name %></td>
                  <td><%= employee.position %></td>
                  <td><%= employee.salary %></td>
                 
              <td><%= link_to 'show', hotel_employee_path(@hotel, employee.id), class: 'btn btn-primary' %></td>
        
              <td>
          <%= link_to 'Edit', edit_hotel_employee_path(@hotel, employee), class: 'btn btn-primary'  %> 
        </td>

              <td><%= link_to "Delete Room", hotel_employee_path(@hotel, employee.id), class: 'btn btn-danger', data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                } %></td>
                </tr>
              <% end %>
            </tbody>


          </table>

          <%= link_to 'New Employee', new_hotel_employee_path, class: 'btn btn-primary' %>

      </div>
    </div>
  </div>
</div>

app/views/employees/new.html.erb
<h1>New Hotel Employee</h1>

<%= render 'form', employee: @employee %>

app/views/employees/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-4 mb-4">
      <div class="card">

        <div class="card-body">
          <h2 class="card-title"> Employee_ID : <%= @employee.id %></h2>
          <h2 class="card-text"> First_Name : <%= @employee.first_name %> </h2>
          <h4 class="card-title"> Position : <%= @employee.position %></h4>

          <%# <a href="#" class="btn btn-primary">Add Rooms</a> %>

        
        </div>
      </div>
    </div>