config/routes.rb
require 'resque/server'
Rails.application.routes.draw do
  get 'payments/index'
  get 'payments/new'
  get 'transacations/index'
 
  get 'wallets/index'
  get 'bookings/new'
  get 'bookings/index'
  get 'reservations/index'
  get 'reservations/show'
  get 'reservations/new'
  get 'reservations/edit'
  # get 'employees/index'
  # get 'employees/show'
  # get 'employees/new'
  # get 'employees/edit'
  get 'employees/allemployee'
  # get 'rooms/index'
  # get 'rooms/show'
  # get 'rooms/new'
  # get 'rooms/edit'
  # get 'hotels/index'
  # get 'hotels/new'
  # get 'hotels/edit'

  # post '/rooms', to: 'rooms#create'
  devise_for :users
  
  root 'main#home'
  get 'main/display', to: 'main#display'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :hotels do
    resources :rooms do 
    end
    resources :employees
    collection do
      post 'import_csv'
    end
    # resources :employees, only: [:index, :new, :create]
  end
  # resources :bookings, only: [:index, :new, :create, :show, :edit, :update, :destroy]

  resources :bookings 
  
  resources :payments
  
  # resources :payments

  resources :dashboard

  resources :checkout, only: [:create]

  resources :main

  authenticate :user do
    mount Resque::Server.new, at: '/jobs'
  end

  # authenticate :user, -> (u) {u.id == 11} do
  #   mount Resque::Server.new, at: '/jobs'
  # end


  # resources :products

  post 'checkout/create', to: 'checkout#create'
  # resources :checkout




  get 'rooms/allrooms', to: 'rooms#allrooms';
  get 'rooms/roominsidehotel', to: 'rooms#roominsidehotel';


  get 'main/hotelrooms/:hotel_id', to: 'main#hotelrooms', as: 'test'

  get 'rooms/hotelallrooms', to: 'rooms#hotelallrooms'

  # get 'payments/new', to: 'payments#new'
  # get 'payments/create', to: 'payments#create'

  resources :payments
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :room
  belongs_to :user
  has_many :payments
  has_one :wallet

  # validates :check_in_date, :check_out_date, presence: true
  # validate :check_out_after_check_in
  # validate :check_room_availability

  # validates_uniqueness_of :room_id, scope: :date

  # private

  # def check_out_after_check_in
  #   return if check_in_date.blank? || check_out_date.blank?

  #   errors.add(:check_out_date, 'must be after check-in date') if check_out_date <= check_in_date
  # end

  # def check_room_availability
  #   return if room.nil?

  #   overlapping_bookings = room.bookings.where(
  #     "(check_in_date <= ? AND check_out_date >= ?) OR (check_in_date <= ? AND check_out_date >= ?)",
  #     check_in_date, check_in_date, check_out_date, check_out_date)

  #   errors.add(:base, 'Room is not available for the selected dates') if overlapping_bookings.exists?
  # end
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :hotel

  
end

app/models/hotel.rb
# require 'csv'

class Hotel < ApplicationRecord
    has_many :rooms, dependent: :destroy
    has_many :employees, dependent: :destroy
    # has_many :bookings, dependent: :destroy

  
    has_one_attached :hotel_photo, dependent: :destroy 
    
    # def self.to_csv 
    #     # attributes = %w{name address contact_number email description}
    #     attributes = Hotel.column_names
        
    #     CSV.generate(headers: true) do |csv|
    #     csv << attributes 

    #         all.each do |employee|
    #             csv << attributes.map {|attr| employee.send(attr)}
    #         end
    #     end
    # end 
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :booking
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/room.rb
require 'csv'
class Room < ApplicationRecord
  belongs_to :hotel
  has_one_attached :room_photo
  has_many :bookings, dependent: :destroy 


  # enum status: { available: 0, booked: 1 }

  # def available?
  #   status == 'available'
  # end




  
  def available?(check_in_date, check_out_date)
    overlapping_bookings = bookings.where(
      "(check_in_date <= ? AND check_out_date >= ?) OR (check_in_date <= ? AND check_out_date >= ?)",
      check_in_date, check_in_date, check_out_date, check_out_date
    )

    overlapping_bookings.empty?
  end
  
end
 

app/models/transacation.rb
class Transacation < ApplicationRecord
  belongs_to :user
  
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_many :bookings

    has_one :wallet
    has_many :transacations
end
 

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :booking
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
    
    @rooms = Room.all

    @hotels = Hotel.all

  end

  def show 
    @room = Room.find(params[:id])
   
  end

  def roomdisplay
    @rooms = Room.find(params[:id])
  end

  def hotelrooms 
    @hotel = Hotel.find(params[:hotel_id])
    puts @hotel
    @rooms = @hotel.rooms
    puts "========================="
    puts @room



  end

  def book 
  end


end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # def allrooms 
  #   @rooms = Room.all
  # end 
  
  def index
    # @rooms = Room.all

    @hotel = Hotel.find params[:hotel_id]
    @rooms = @hotel.rooms


    #   respond_to do |format|
    #   format.html
    #   format.csv  do 
    #     csv_data = CsvExportService.new(@rooms).generate_csv
    #     send_data csv_data, filename: "rooms- #{Date.today}.csv"
    #   end
    #  end

  end

 

  def show
    # puts "===================================="
    # puts params
    # puts "===================================="
    @room = Room.find(params[:id])

  end

  def new
    @room = Room.new
    @hotel = Hotel.find(params[:hotel_id])
  end

  def create 
    @hotel = Hotel.find(params[:hotel_id])

    @room = @hotel.rooms.create(room_params)
    redirect_to hotel_path(@hotel)
  end
  

  def edit 
      @hotel = Hotel.find(params[:id])
      @room = @hotel.rooms.find(params[:id])
  end

  def update
    if @room.update(room_params)
      redirect_to @hotel, notice: 'Room was successfully updated.'
    else
      render :edit
    end
  end
 

  def destroy 
    @room = Room.find(params[:id])
    @room.destroy 

    redirect_to root_path
  end






  # def search
  #   @hotel = Hotel.find(params[:hotel_id])
  #   # @check_in_date = params[:check_in_date]
  #   # @check_out_date = params[:check_out_date]
  #   # @guests = params[:guests]

  #   # @available_rooms = Room.available_rooms(@check_in_date, @check_out_date, @guests, @hotel)
  #   @available_rooms = Room.available_rooms(@hotel)

  # end

  # def available_rooms
  #   @check_in_date = params[:check_in_date]
  #   @check_out_date = params[:check_out_date]
  #   # @guests = params[:guests]
  #   @available_rooms = Room.available_rooms(@check_in_date, @check_out_date)
  # end


  private 
  def room_params 
    params.require(:room).permit(:price,:room_type,:occupancy, :room_photo, :capacity, :floor_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/rooms/_form.html.erb
<section>
  <div class='container mt-5 pt-5' >
    <div class='row' >
      <div class='col-12 col-sm-8 col-md-6 m-auto'>
        <div class='card border-0 shadow' >
          <div class='card-body'>
           
              <%= form_with model: [ hotel, hotel.rooms.build ] do |form| %>
              <div>
                <%= form.label :price %><br>
                <%= form.text_field :price, class: "form-control my-3 py-2" %>
                <% @room.errors.full_messages_for(:price).each do |message| %>
                  <div><%= message %></div>
                <% end %>
              </div>

              <div>
                <%= form.label :room_type %><br>
                <%= form.text_field :room_type, class: "form-control my-3 py-2"%><br>
                <% @room.errors.full_messages_for(:room_type).each do |message| %>
                  <div><%= message %></div>
                <% end %>
              </div>

              <div>
                <%= form.label :occupancy %><br>
                <%= form.text_field :occupancy, class: "form-control my-3 py-2" %><br>
                <% @room.errors.full_messages_for(:occupancy).each do |message| %>
                  <div><%= message %></div>
                <% end %>
              </div>

              <div>
                <%= form.label :capacity %><br>
                <%= form.text_field :capacity, class: "form-control my-3 py-2" %><br>
                <% @room.errors.full_messages_for(:capacity).each do |message| %>
                  <div><%= message %></div>
                <% end %>
              </div>

              <div>
                <%= form.label :floor_number %><br>
                <%= form.text_field :floor_number, class: "form-control my-3 py-2" %><br>
                <% @room.errors.full_messages_for(:floor_number).each do |message| %>
                  <div><%= message %></div>
                <% end %>
              </div>

              <div>
                <%= form.label :room_photo %><br>
                <%= form.file_field :room_photo, class: "form-control my-3 py-2" %><br>
                <% @room.errors.full_messages_for(:room_photo).each do |message| %>
                  <div><%= message %></div>
                <% end %>
              </div>

               <div>
                <%= form.submit %>
              </div>
              
            <% end %>

            </div>

             

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/rooms/allrooms.html.erb
<div class="container">
  <div class="row">
    <%# <div class="col-md-8 col-xs-12"> %>
      <div class="table-responsive">

        <h1>Listing Room</h1>
          <table class="table table-bordered table-hover table-dark table-striped">
            <thead>
              <tr>
              <th>room.id</th>
                <th>Price</th>
                <th>room_type</th>
                <th>Occupancy</th>
                <th colspan="3">Actions</th>
              </tr>
            </thead>

         <tbody>
              <% @rooms.each do |room| %>
                <tr>
                  <td><%= room.id %></td>
                  <td><%= room.price %></td>
                  <td><%= room.room_type %></td>
                  <td><%= room.occupancy %></td>
                  
               
                  <td><%= link_to "Show", '/hotels/3/rooms/2' %></td>
                   
                  
                            

                </tr>
              <% end %>
            </tbody>


          </table>

      <%# <%= link_to 'New Room', new_hotel_room_path, class: 'btn btn-outline-primary' %> 
      </div>
    </div>
  </div>
</div>

app/views/rooms/edit.html.erb
<%= render 'form', hotel: @hotel %>

<!-- 
<section>
  <div class='container mt-5 pt-5' >
    <div class='row' >
      <div class='col-12 col-sm-8 col-md-6 m-auto'>
        <div class='card border-0 shadow' >
          <div class='card-body'>
           
              <%= form_with model: [ @hotel, @hotel.rooms.build ] do |form| %>
              <div>
                <%= form.label :price %><br>
                <%= form.text_field :price, class: "form-control my-3 py-2" %>
                <% @room.errors.full_messages_for(:price).each do |message| %>
                  <div><%= message %></div>
                <% end %>
              </div>

              <div>
                <%= form.label :room_type %><br>
                <%= form.text_field :room_type, class: "form-control my-3 py-2"%><br>
                <% @room.errors.full_messages_for(:room_type).each do |message| %>
                  <div><%= message %></div>
                <% end %>
              </div>

              <div>
                <%= form.label :occupancy %><br>
                <%= form.text_field :occupancy, class: "form-control my-3 py-2" %><br>
                <% @room.errors.full_messages_for(:occupancy).each do |message| %>
                  <div><%= message %></div>
                <% end %>
              </div>

               <div>
                <%= form.submit %>
              </div>
              
            <% end %>

            </div>

             

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

--> 

app/views/rooms/index.html.erb
<div class="container">
  <div class="row">
    <%# <div class="col-md-8 col-xs-12"> %>
      <div class="table-responsive">

        <h1>Listing Room</h1>
          <table class="table table-bordered table-hover table-dark table-striped">
            <thead>
              <tr>
              <th>room.id</th>
                <th>Room_Type</th>
                <th>Price</th>
                <th>Occupancy</th>
                <th colspan="3">Actions</th>
              </tr>
            </thead>

         <tbody>
              <% @rooms.each do |room| %>
                <tr>
                  <td><%= room.id %></td>
                  <td><%= room.room_type %></td>
                  <td><%= room.price %></td>
                  <td><%= room.occupancy %></td>
                  
                <td><%= link_to "Show Room", hotel_room_path(@hotel, room.id) %></td>
                <td><%= link_to "Edit Room", edit_hotel_room_path(@hotel, room.id) %></td>
                
          
                </tr>
              <% end %>
            </tbody>

          </table>
     
      <%= link_to 'New Room', new_hotel_room_path, class: 'btn btn-outline-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<%= render 'form', hotel: @hotel%>

app/views/rooms/roominsidehotel.html.erb
<!-- our_room -->
      <div  class="our_room" id="rooms">
         <div class="container">
            <div class="row">
               <div class="col-md-12">
                  <div class="titlepage">
                     <h2>Our Room</h2>
                     <p>Lorem Ipsum available, but the majority have suffered </p>
                  </div>
               </div>
            </div>

            <div class="row">
            
               <% @rooms.each do |room| %>
               <div class="col-md-4 col-sm-6 d-flex ">
                  <div id="serv_hover"  class="room">

                     <div class="room_img">
                        <%= image_tag room.room_photo %>

                     </div>
                     <div class="bed_room">
                        <h3>Room Price : <%= room.price %> </h3>
                        <p>Room_type : <%= room.room_type %></p>
                        <%# <%= link_to 'Book Now', new_dashboard_path, class: 'btn btn-primary' %>
                        <%= link_to 'Book Now', new_booking_path, class: 'btn btn-primary' %>

                        
                     </div>

                  </div>
               </div>
                  <% end %>
               
              
               
               
            </div>
         </div>
      </div>
      <!-- end our_room -->

app/views/rooms/search.html.erb
<!-- app/views/rooms/search.html.erb -->
<h1>Search Available Rooms</h1>

<%= form_tag available_rooms_path, method: :get do %>
  <%= label_tag 'check_in_date', 'Check-in Date' %>
  <%= text_field_tag 'check_in_date', nil, type: 'date' %>

  <%= label_tag 'check_out_date', 'Check-out Date' %>
  <%= text_field_tag 'check_out_date', nil, type: 'date' %>

  <%= label_tag 'guests', 'Number of Guests' %>
  <%= number_field_tag 'guests', 1, min: 1 %>

  <%= submit_tag 'Search' %>
<% end %>

<% if @available_rooms.any? %>
  <h2>Available Rooms</h2>
  <ul>
    <% @available_rooms.each do |room| %>
      <li><%= room.name %></li>
    <% end %>
  </ul>
<% else %>
  <p>No available rooms for the selected dates and guests.</p>
<% end %>

app/views/rooms/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-4 mb-4">
      <div class="card">

        <div class="card-body">
          <h2 class="card-title"> Room_ID : <%= @room.id %></h2>
          <h4 class="card-title"> RoomType : <%= @room.room_type %></h4>

          <h6 class="card-text"> RoomRent : <%= @room.price %> </h6>
          <%# <a href="#" class="btn btn-primary">Add Rooms</a> %>
        <%= image_tag @room.room_photo %>
        
        </div>
      </div>
    </div>