config/routes.rb
require 'resque/server'
Rails.application.routes.draw do
  get 'payments/index'
  get 'payments/new'
  get 'transacations/index'
 
  get 'wallets/index'
  get 'bookings/new'
  get 'bookings/index'
  get 'reservations/index'
  get 'reservations/show'
  get 'reservations/new'
  get 'reservations/edit'
  # get 'employees/index'
  # get 'employees/show'
  # get 'employees/new'
  # get 'employees/edit'
  get 'employees/allemployee'
  # get 'rooms/index'
  # get 'rooms/show'
  # get 'rooms/new'
  # get 'rooms/edit'
  # get 'hotels/index'
  # get 'hotels/new'
  # get 'hotels/edit'

  # post '/rooms', to: 'rooms#create'
  devise_for :users
  
  root 'main#home'
  get 'main/display', to: 'main#display'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :hotels do
    resources :rooms do 
    end
    resources :employees
    collection do
      post 'import_csv'
    end
    # resources :employees, only: [:index, :new, :create]
  end
  # resources :bookings, only: [:index, :new, :create, :show, :edit, :update, :destroy]

  resources :bookings 
  
  resources :payments
  
  # resources :payments

  resources :dashboard

  resources :checkout, only: [:create]

  resources :main

  authenticate :user do
    mount Resque::Server.new, at: '/jobs'
  end

  # authenticate :user, -> (u) {u.id == 11} do
  #   mount Resque::Server.new, at: '/jobs'
  # end


  # resources :products

  post 'checkout/create', to: 'checkout#create'
  # resources :checkout




  get 'rooms/allrooms', to: 'rooms#allrooms';
  get 'rooms/roominsidehotel', to: 'rooms#roominsidehotel';


  get 'main/hotelrooms/:hotel_id', to: 'main#hotelrooms', as: 'test'

  get 'rooms/hotelallrooms', to: 'rooms#hotelallrooms'

  # get 'payments/new', to: 'payments#new'
  # get 'payments/create', to: 'payments#create'

  resources :payments
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :room
  belongs_to :user
  has_many :payments
  has_one :wallet

  # validates :check_in_date, :check_out_date, presence: true
  # validate :check_out_after_check_in
  # validate :check_room_availability

  # validates_uniqueness_of :room_id, scope: :date

  # private

  # def check_out_after_check_in
  #   return if check_in_date.blank? || check_out_date.blank?

  #   errors.add(:check_out_date, 'must be after check-in date') if check_out_date <= check_in_date
  # end

  # def check_room_availability
  #   return if room.nil?

  #   overlapping_bookings = room.bookings.where(
  #     "(check_in_date <= ? AND check_out_date >= ?) OR (check_in_date <= ? AND check_out_date >= ?)",
  #     check_in_date, check_in_date, check_out_date, check_out_date)

  #   errors.add(:base, 'Room is not available for the selected dates') if overlapping_bookings.exists?
  # end
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :hotel

  
end

app/models/hotel.rb
# require 'csv'

class Hotel < ApplicationRecord
    has_many :rooms, dependent: :destroy
    has_many :employees, dependent: :destroy
    # has_many :bookings, dependent: :destroy

  
    has_one_attached :hotel_photo, dependent: :destroy 
    
    # def self.to_csv 
    #     # attributes = %w{name address contact_number email description}
    #     attributes = Hotel.column_names
        
    #     CSV.generate(headers: true) do |csv|
    #     csv << attributes 

    #         all.each do |employee|
    #             csv << attributes.map {|attr| employee.send(attr)}
    #         end
    #     end
    # end 
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :booking
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/room.rb
require 'csv'
class Room < ApplicationRecord
  belongs_to :hotel
  has_one_attached :room_photo
  has_many :bookings, dependent: :destroy 


  # enum status: { available: 0, booked: 1 }

  # def available?
  #   status == 'available'
  # end




  
  def available?(check_in_date, check_out_date)
    overlapping_bookings = bookings.where(
      "(check_in_date <= ? AND check_out_date >= ?) OR (check_in_date <= ? AND check_out_date >= ?)",
      check_in_date, check_in_date, check_out_date, check_out_date
    )

    overlapping_bookings.empty?
  end
  
end
 

app/models/transacation.rb
class Transacation < ApplicationRecord
  belongs_to :user
  
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_many :bookings

    has_one :wallet
    has_many :transacations
end
 

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :booking
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  def index
    @hotels = Hotel.all

    # respond_to do |format|
    #   format.html
    #   format.pdf do
    #     render pdf: "AlleHotel", template: "hotels/index", formats: [:html], layouts: "pdf ",
    #     orientation:                    'Landscape',
    #     page_size: 'A4'

    #     # Excluding ".pdf" extension.
    #   end
    # end
    
    respond_to do |format|
      format.html
      # format.csv { send_data @hotels.to_csv, filename: "hotels-#{Date.today}.csv" }
      format.csv { send_data CsvExportService.new(@hotels).to_csv, filename: "hotels-#{Date.today}.csv" }
    end
    
  end

  def show
    @hotel = Hotel.find(params[:id])
  end

  def new
    @hotel = Hotel.new
    
  end

  def create
    @hotel = Hotel.new(hotel_params)

    if @hotel.save
      
      # CrudNotificationMailer.create_notification(@hotel).deliver_now
      # UserImportJob.perform_latter(@hotel.id)
      UserImportJob.set(wait_until: @hotel.schedule_at).perform_latter(@hotel.id)

      redirect_to hotels_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @hotel = Hotel.find(params[:id])
  end

  def update
    @hotel = Hotel.find(params[:id])

    if @hotel.update(hotel_params)
      
      # CrudNotificationMailer.update_notification(@hotel).deliver_now

      redirect_to @hotel
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @hotel = Hotel.find(params[:id])

    # CrudNotificationMailer.delete_notification(@hotel).deliver_now
    
    @hotel.destroy

    redirect_to root_path, status: :see_other
  end




  def import_csv
    csv_file = params[:file]
    CSV.foreach(csv_file.path, headers: true) do |row|
      Hotel.create(row.to_h)
    end
    redirect_to hotels_path, notice: 'CSV imported successfully'
  end
  
  

  private
    def hotel_params
      params.require(:hotel).permit(:name, :email, :contact_number, :address, :description, :hotel_photo)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
    
    @rooms = Room.all

    @hotels = Hotel.all

  end

  def show 
    @room = Room.find(params[:id])
   
  end

  def roomdisplay
    @rooms = Room.find(params[:id])
  end

  def hotelrooms 
    @hotel = Hotel.find(params[:hotel_id])
    puts @hotel
    @rooms = @hotel.rooms
    puts "========================="
    puts @room



  end

  def book 
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/hotels/_form.html.erb
<section>
  <div class='container mt-5 pt-5' >
    <div class='row' >
      <div class='col-12 col-sm-8 col-md-6 m-auto'>
        <div class='card border-0 shadow' >
          <div class='card-body'>
            <%= form_with model: @hotel do |form| %>
              <div>
                <%= form.label :name %><br>
                <%= form.text_field :name, class: "form-control my-3 py-2" %>
                <% @hotel.errors.full_messages_for(:name).each do |message| %>
                  <div><%= message %></div>
                <% end %>
              </div>

              <div>
                <%= form.label :email %><br>
                <%= form.text_field :email, class: "form-control my-3 py-2"%><br>
                <% @hotel.errors.full_messages_for(:email).each do |message| %>
                  <div><%= message %></div>
                <% end %>
              </div>

              <div>
                <%= form.label :contact_number %><br>
                <%= form.text_field :contact_number, class: "form-control my-3 py-2" %><br>
                <% @hotel.errors.full_messages_for(:contact_number).each do |message| %>
                  <div><%= message %></div>
                <% end %>
              </div>

              <div>
                <%= form.label :address %><br>
                <%= form.text_area :address, class: "form-control my-3 py-2" %><br>
                <% @hotel.errors.full_messages_for(:address).each do |message| %>
                  <div><%= message %></div>
                <% end %>
              </div>

              <div>
                <%= form.label :description %><br>
                <%= form.text_area :description, class: "form-control my-3 py-2" %><br>
                <% @hotel.errors.full_messages_for(:description).each do |message| %>
                  <div><%= message %></div>
                <% end %>
              </div>

               <div>
                <%= form.label :hotel_photo %><br>
                <%= form.file_field :hotel_photo, class: "form-control my-3 py-2" %><br>
                <% @hotel.errors.full_messages_for(:description).each do |message| %>
                  <div><%= message %></div>
                <% end %>
              </div>

              <div>
                <%= form.submit %>
              </div>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/hotels/edit.html.erb
<%=  render 'form' %>

app/views/hotels/index.html.erb
<div class="container">
  <div class="row">
    <%# <div class="col-md-8 col-xs-12"> %>
      <div class="table-responsive">

        <h1>Listing Hotels</h1>
          <table class="table table-bordered table-hover table-dark table-striped">
            <thead>
              <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Contact_Number</th>
                <th>Address</th>
                <th>Description</th>

                <th colspan="3">Actions</th>
              </tr>
            </thead>

            <tbody>
              <% @hotels.each do |hotel| %>
                <tr>
                  <td><%= hotel.name %></td>
                  <td><%= hotel.email %></td>
                  <td><%= hotel.contact_number %></td>
                  <td><%= hotel.address %></td>
                  <td><%= hotel.description %></td>
                  <td><%= link_to "Show", hotel_path(hotel)%></td>
                  <td><%= link_to "Edit", edit_hotel_path(hotel) %></td>
                  <td><%= button_to "Destroy", hotel_path(hotel), method: :delete %>
                  </td>

                </tr>
              <% end %>
            </tbody>
          </table>

          <%= form_tag import_csv_hotels_path, multipart: true do %>
          <%= file_field_tag :file %>
          <%= submit_tag 'Import CSV' %>
        <% end %>
        
        <%= link_to "New hotel", new_hotel_path, class: 'btn btn-outline-primary'  %>

        <%= link_to "AllHotelPDF", hotels_path(format: :pdf), layouts: 'pdf' %>

      </div>
    </div>
  </div>
</div>

app/views/hotels/new.html.erb
<%= render "form", hotel: @hotel %>

app/views/hotels/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-5 mb-5">
      <div class="card">
       
       <!--
        <%= image_tag 'blog1.jpg', class:'img-fiuld' %>
      -->

        <div class="card-body">
          <td> <%= image_tag @hotel.hotel_photo, class: 'img-fuild' %> </td>

          <h2 class="card-title"> Hotel_ID : <%= @hotel.id %></h2>
          <h4 class="card-title"> HotelName : <%= @hotel.name %></h4>

          <h6 class="card-text"> HotelDescription : <%= @hotel.description %> </h6>
          

          <%# <a href="#" class="btn btn-primary">Add Rooms</a> %>

          <%= link_to 'Add Rooms',hotel_rooms_path(@hotel), class: 'btn btn-outline-success' %>
          <%# <a href="#" class="btn btn-primary">Add Employee</a> %>
          <%= link_to 'Add Employee', hotel_employees_path(@hotel) ,class: 'btn btn-primary' %>
          </div>
      </div>
    </div>




  </div>
</div>